### ISSUE TITLE
The model does not perform as expected on KITTI.

### ISSUE THREAD

**Issue by xiazhongyv** [PointsCoder/Pyramid-RCNN#7]
In your paper:  val AP@R11
PV-RCNN      89.35 83.69 78.70
Pyramid-PV   89.37 84.38 78.84

My result: val AP@R40
PV-RCNN      orange
Pyramid-PV   blue

![val](https://user-images.githubusercontent.com/45617755/147315530-9865de23-55eb-4dc1-8bf2-5ada3f043689.png)

**Comment by xiazhongyv** [comment]
Hello, I have tried to train your model and PVRCNN on PCDet, but the actual results are somewhat different. May I ask if there are key points for training to pay attention to, or pre-trained model？

**Comment by PointsCoder** [comment]
@xiazhongyv This repo is obtained from our working repo. I am not sure what I have changed from the original pcdet repo since too many modifications were made. 

So If you want to reproduce, plz use this repo and completely follow the training configs. I can personally obtain the reported results before releasing this repo.

**Comment by PointsCoder** [comment]
Closed if no other issues.
